name = "restreamer-image-uploader"

routes = [
    { pattern = "live.rollmann-rollt.de", custom_domain = true }
]
main = "index.js"
workers_dev = true
compatibility_date = "2024-02-16"

[[r2_buckets]]
binding = 'snapshot_bucket' # <~ valid JavaScript variable name
bucket_name = 'rollmann-rollt-snapshots'